spring:
  application:
    name: webshopapi

  datasource:
    url: jdbc:mysql://localhost:3306/webshop?serverTimezone=UTC
    username: root
    password: Password123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
